# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6dcc651454dbfc086ee00616d971c29c4bf4daf915a9c95735137916e9963e01aef9b9d625846f65d97d909e9e0cc30fdb98c4a6713ae827dd8ec181a527b605

test:
  secret_key_base: 2724f4e650e54498a644b206ec287c8a9e0eb67bbf119cb008df084d69ef045b082574d9232ccab1ffc29d8ae943a86ad555f9ddacf4f434e8382e797e7c435b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
